article/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="article"
urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
# from article.views import index
from article import views
#FileUpload için
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index,name="index"),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),

]

#FileUpload için eklendi
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    #models.CASCADE bağlı olunan auth.User tablosundaki  #user'ımız silinirse o user'a ait article'larında silinmesini sağlar
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="yazar")      
    title=models.CharField(max_length=250,verbose_name="başlık")
    content=RichTextField()
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma tarihi")
    article_image=models.FileField(blank=True,null=True,verbose_name="Makaleye fotoğraf ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    #yukarıdaki kodda related_name özelliği bizim ileride Article.comments ile bu Article'a bağlı commentlere de ulaşabilmemizi sağlayacaktır.
    comment_author=models.CharField(max_length=50,verbose_name="İsim")
    comment_content=models.CharField(max_length=200,verbose_name="Yorum")
    comment_date=models.DateTimeField(auto_now_add=True )
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']
    # sıralama tarihte son yapılan yorum ilk gösterilir

article/forms.py
from django import forms
from .models import Article     #Article modelimizi import ediyoruz

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article       # Formumuzla Article modelimizi bağladık
        fields=["title","content","article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from .forms import ArticleForm      #Şuanki klasörümüzün içindeki forms dosyasından ArticleForm'u aldık
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def articles(request):
    keyword=request.GET.get("keyword")
    if keyword:
        articles=Article.objects.filter(title__contains=keyword)
        return render(request,"articles.html",{"articles":articles})

    articles=Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

# Create your views here.
def index(request):
    context={  
        "number1":10,
        "number2":20
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")
#@login_required decorator'ı aşağıdaki fonksiyon ile gidilen sayfanın sadece giriş yapıldıysa görüntülenmesini sağlar
@login_required(login_url="user:login")
def dashboard(request):
    articles=Article.objects.filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)
#@login_required decorator'ı aşağıdaki fonksiyon ile gidilen sayfanın sadece giriş yapıldıysa görüntülenmesini sağlar
@login_required(login_url="user:login")
def addArticle(request):
    form=ArticleForm(request.POST or None,request.FILES or None)  

    if form.is_valid():
        article=form.save(commit=False)     #############  article'ın author bilgisi olmadan kaydedilmemesi için henüz veritabanına commit etme dedik.
        article.author=request.user
        article.save()          #commit=True olur ve vt'ye article kaydedilir.

        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("article:dashboard")
    
    return render(request,"addArticle.html",{"form":form})

def detail(request,id):
    # article=Article.objects.filter(id=id).first()       #.first yazmaz isek bir queryset dönmekte.
    article=get_object_or_404(Article,id=id)
    comments=article.comments.all()
    #modelimizde commet sınıfımızdaki fk'nın related_name özelliğine comments dediğimiz için article'ın tüm commentlerine ulaşabiliriz. comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})


#@login_required decorator'ı aşağıdaki fonksiyon ile gidilen sayfanın sadece giriş yapıldıysa görüntülenmesini sağlar
@login_required(login_url="user:login")
def updateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form=ArticleForm(request.POST or None,request.FILES or None,instance=article)   #instance parametresine buradaki objeyi gönderirsek objedeki bilgiler article formunun içine yazılır
    #yani instance formun dolu gelmesini sağlar
    if form.is_valid():
        article=form.save(commit=False)     #############  article'ın author bilgisi olmadan kaydedilmemesi için henüz veritabanına commit etme dedik.
        article.author=request.user
        article.save()          #commit=True olur ve vt'ye article kaydedilir.

        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})
#@login_required decorator'ı aşağıdaki fonksiyon ile gidilen sayfanın sadece giriş yapıldıysa görüntülenmesini sağlar
@login_required(login_url="user:login")
def deleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()

    messages.success(request,"Makale başarıyla silindi")
    return redirect("article:dashboard")

def addComment(request,id):
    article=get_object_or_404(Article,id = id)

    if request.method=="POST":
        comment_author=request.POST.get("comment_author")
        comment_content=request.POST.get("comment_content")
        newComment=Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article=article
        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))
    # reverse fonksiyonu dinamik bir url yönlendirmek için kullanılıyor
    # örnekte kwargs ile dinamik olarak id mizi yolladık ve istediğimiz sayfaya yönlendirme yaptık 

templates/about.html
{% extends "layout.html" %}
{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>Selamlar</p>
{% endblock body %}

templates/addArticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.media }}  <!-- ckeditör için gerekli --->
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kaydet</button>

        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}


<div class="row">
    <div class="col-md-10 offset-md-3" style="text-align:center">
        <div class="col-lg-8">
            <h3>Makaleler</h3>
            <hr>
            <form action="">
                {% csrf_token %}
                <input type="text" name="keyword" class="input-sm">
                <button type="submit" class="btn btn-danger">Ara</button>
                <hr>
            </form>
        </div>
    </div>
</div>

{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <a href="{% url 'article:detail' article.id %}"> <h1 class="mt-4">{{article.title}}</h1> </a>

            <!-- Author -->
            <p class="lead">
                {{article.author}}
            </p>

            <hr>

            <!-- Date/Time -->
            <p>{{article.created_date}}</p>

            <hr>

            <!-- Preview Image -->
            {% if article.article_image %}
            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
            {% endif %}


            <hr>

            <!-- Post Content -->
            <p class="lead">
                {{article.content|safe|truncatewords:10}}
            </p>

            <a href="{% url 'article:detail' article.id %}" class="btn btn-danger" style="float:right;">Devamını Oku</a>

            <hr>


        </div>
    </div>
</div>
<!-- /.row -->
{% endfor %}

{% else %}
<div class="row">
    <div class="col-md-10 offset-md-3" style="text-align:center">
        <div class="col-lg-8">
            <div class="alert alert-danger">
                Makale bulunamadı
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz , <small>{{request.user.username}}</small>
</p>
<hr>
<a href="{% url 'article:addarticle' %}" class="btn btn-danger">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-danger">
    Henüz bir makaleniz bulunmuyor
</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}

<div class="row">

  <!-- Post Content Column -->
  <div class="col-lg-8 offset-2">

    <!-- Title -->
    <h1 class="mt-4">{{article.title}}</h1>

    <!-- Author -->
    <p class="lead">
      {{article.author}}
    </p>

    <hr>

    <!-- Date/Time -->
    <p>{{article.created_date}}</p>

    <hr>
    <div class="col-lg-8 offset-2">
    <!-- Preview Image -->
    {% if article.article_image %}
    <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
    {% endif %}
    </div>

    <hr>

    <!-- Post Content -->
    <p class="lead">
      {{article.content|safe}}
    </p>

    <hr>
    <h4>Yorumlar</h4>
    <hr>
    {% if comments %}
      {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}}
            <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
    {% else %}
    <div class="alert alert-danger">
     Bu makaleye herhangi bir yorum yapılmamış.
    </div>
    {% endif %}

    <!-- Comments Form -->
    <div class="card my-4">
      <h5 class="card-header">Yorum Ekle:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'article:comment' article.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">İsim</label>
            <input name="comment_author" type="text" class="form-control"  placeholder="İsminizi girin...">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Yorum</label>
            <textarea name="comment_content" class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-danger">Ekle</button>
        </form>
      </div>
    </div>
  </div>

</div>
<!-- /.row -->

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}

    <div class="jumbotron text-center">
        <h3>Selçuk Akarın'ın bloğuna hoşgeldin</h3>
        <p>Bu blog'taki yazılar kendi karşılaştığım hatalar üzerinedir. </p>
    </div>
    <p>
        {% if request.user.is_authenticated %}      <!-- request.user sisteme giriş yapmış user'a erişir -->
            giriş yapılmış, {{request.user.username}}
        {% else %}
            giriş yapılmamış
        {% endif %}
    </p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
    <title>Selçuk Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div class="container" style="margin-top:5em; margin-bottom:5em;">
    
    {% if messages %}
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
    {% endif %}
    <div class="alert alert-info">Bu proje Django ile yakın bir vakitte hayata geçmiştir. Ve geliştirmeler yazılımcısının zaman bulması ile devam edecektir.</div>
        {% block body %}
        
        {% endblock body %}
    </div>


<script src="{% static 'js/bootstrap.js'%}"></script>
<script src="{% static 'js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş yap</h3>
        <hr>
        <form method="post">

            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>

        </form>
    </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt ol</h3>
        <hr>
        <form method="post">

            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kayıt ol</button>

        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.media }}  <!-- ckeditör için gerekli --->
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kaydet</button>

        </form>
    </div>
</div>
{% endblock body %}